#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

bspc config border_width        2.5
bspc config window_gap          25

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

darkblue="#6272a4"
cyan="#00AEEF"
red="#ff5555"
white="#f8f8f2"
black="#282a36"
purple="#bd93f9"
darkpurp="#301934"
yellowbrown="#e1b700"
bspc config focused_border_color        $cyan
bspc config normal_border_color         $white
