#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config top_padding 0
bspc config bottom_padding 0

picom --experimental-backends -b > /dev/null 2>&1
nitrogen --restore > /dev/null 2>&1
$HOME/polybar-collection/launch.sh > /dev/null 2>&1
xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 165 &

bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

bspc config border_width        3
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

darkblue="#6272a4"
cyan="#00AEEF"
red="#ff5555"
white="#f8f8f2"
black="#282a36"
purple="#bd93f9"
darkpurp="#301934"
yellowbrown="#e1b700"
grey="#808080"
bspc config focused_border_color        $grey
bspc config normal_border_color         $grey
