#! /bin/bash
ROOT_DIR="$HOME/config-switcher"
SRC_DIR="$HOME/config-switcher/src"
THEME_DIR="$HOME/config-switcher/themes"
WALLPAPER_DIR="$HOME/config-switcher/wallpapers"

function check_dir () {
    local dir="$1"
    if [ ! -d "$HOME/.config/$dir" ]; then
        mkdir "$HOME/.config/$dir"
    fi
}
> $SRC_DIR/themes.txt

cd $THEME_DIR
for i in *; do
    echo $i >> $SRC_DIR/themes.txt
done

cd "$HOME/config-switcher/src" || exit

./main $SRC_DIR/themes.txt
mapfile -t vars < tmp.txt 

theme=${vars[0]} 
wm=${vars[1]}
term=${vars[2]}

rm -rf themes.txt
rm -rf tmp.txt

if [ ! -d "$HOME/.config/rofi" ]; then
    cp -r "$ROOT_DIR/globals/rofi" "$HOME/.config/"
fi

if [ ! -d "$HOME/polybar-collection" ]; then
    cp -r "$ROOT_DIR/globals/polybar-collection" "$HOME"
fi

if [ ! -d "$HOME/polybar-scripts" ]; then
    cp -r "$ROOT_DIR/globals/polybar-scripts" "$HOME"
fi

check_dir "picom"
check_dir "zathura"
check_dir "polybar"

if [ "$theme" = "Catppuccin" ]; then

    wallpaper="$WALLPAPER_DIR/catppuccin.jpg"
    nitrogen --set-zoom-fill "$wallpaper" --save > /dev/null 2>&1
    
    if [ "$term" = "alacritty" ]; then
        check_dir "alacritty"
        cp "$THEME_DIR/Catppuccin/alacritty/alacritty.toml" "$HOME/.config/alacritty/"

    elif [ "$term" = "kitty" ]; then
        check_dir "kitty"
        cp "$THEME_DIR/Catppuccin/kitty/kitty.conf" "$HOME/.config/kitty/"
    fi

    if [ "$wm" = "i3" ]; then
        check_dir "i3"
        cp "$THEME_DIR/Catppuccin/i3/config" "$HOME/.config/i3/"
        if [ "$term" = "kitty" ]; then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/i3/config"
        else
            sed -i 's/kitty/alacritty/g' "$HOME/.config/i3/config"
        fi
    elif [ "$wm" = "bspwm" ]; then
        check_dir "bspwm"
        check_dir "sxhkd"
        cp "$THEME_DIR/Catppuccin/bspwm/bspwmrc" "$HOME/.config/bspwm/"
        cp "$THEME_DIR/Catppuccin/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/"
        if [ "$term" = "kitty" ];then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/sxhkd/sxhkdrc"
        else
            sed -i 's/kitty/alacritty/g' "$HOME/.config/sxhkd/sxhkdrc"
        fi
    fi


    cp "$THEME_DIR/Catppuccin/fish/config.fish" "$HOME/.config/fish/"
    cp "$THEME_DIR/Catppuccin/picom/picom.conf" "$HOME/.config/picom/"
    cp "$THEME_DIR/Catppuccin/zathura/zathurarc" "$HOME/.config/zathura/"
    cp "$THEME_DIR/Catppuccin/polybar-collection/launch.sh" "$HOME/polybar-collection/launch.sh"
    cp "$THEME_DIR/Catppuccin/polybar-collection/modules.ini" "$HOME/polybar-collection/modules.ini"
    
    # TODO
    # nvim configuration changes
    # cp "$THEME_DIR/Catppuccin/nvim/init.lua" "$HOME/.config/nvim/init.lua"
    
    sed -i "/colorscheme/c\vim.cmd('colorscheme catppuccin-mocha')" "$HOME/.config/nvim/init.lua"
    sed -i "/airline_theme/c\vim.g.airline_theme = 'catppuccin'" "$HOME/.config/nvim/init.lua"

    if pgrep picom > /dev/null; then
        pkill picom
    fi

    if pgrep polybar > /dev/null; then
        pkill polybar
        while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    fi

    [ "$wm" = "bspwm" ] && bspc wm -r
    [ "$wm" = "i3" ] && i3-msg restart
    [ "$wm" = "bspwm" ] && pkill -USR1 -x sxhkd
    [ "$term" = "kitty" ] && kill -SIGUSR1 $(pgrep kitty)

    clear; exec fish

elif [ "$theme" = "gruvbox" ]; then

    wallpaper="$WALLPAPER_DIR/gruv.jpg"
    nitrogen --set-zoom-fill "$wallpaper" --save > /dev/null 2>&1

    if [ "$term" = "alacritty" ]; then
        check_dir "alacritty"
        cp "$THEME_DIR/gruvbox/alacritty/alacritty.toml" "$HOME/.config/alacritty/"
    elif [ "$term" = "kitty" ]; then
        check_dir "kitty"
        cp "$THEME_DIR/gruvbox/kitty/kitty.conf" "$HOME/.config/kitty/"
    elif [ "$term" = "urxvt" ]; then
        cp "$THEME_DIR/gruvbox/urxvt/.Xresources" "$HOME/.Xresources"
    fi

    if [ "$wm" = "i3" ]; then
        check_dir "i3"
        cp "$THEME_DIR/gruvbox/i3/config" "$HOME/.config/i3/"
        if [ "$term" = "kitty" ]; then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/i3/config" || sed -i 's/urxvt/kitty/g' "$HOME/.config/i3/config"
        elif [ "$term" = "urxvt" ]; then
            sed -i 's/alacritty/urxvt -e fish/g' "$HOME/.config/i3/config" || sed -i 's/kitty/urxvt -e fish/g' "$HOME/.config/i3/config"
        else
            sed -i 's/kitty/alacritty/g' "$HOME/.config/i3/config" || sed -i 's/urxvt/alacritty/g' "$HOME/.config/i3/config"
        fi

    elif [ "$wm" = "bspwm" ]; then
        check_dir "bspwm"
        check_dir "sxhkd"
        cp "$THEME_DIR/gruvbox/bspwm/bspwmrc" "$HOME/.config/bspwm/"
        cp "$THEME_DIR/gruvbox/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/"
        if [ "$term" = "kitty" ]; then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/sxhkd/sxhkdrc" || sed -i 's/urxvt/kitty/g' "$HOME/.config/sxhkd/sxhkdrc"
        elif [ "$term" = "urxvt" ]; then
            sed -i 's/alacritty/urxvt -e fish/g' "$HOME/.config/sxhkd/sxhkdrc" || sed -i 's/kitty/urxvt -e fish/g' "$HOME/.config/sxhkd/sxhkdrc"
        else
            sed -i 's/kitty/alacritty/g' "$HOME/.config/sxhkd/sxhkdrc" || sed -i 's/urxvt/alacritty/g' "$HOME/.config/sxhkd/sxhkdrc"
        fi
    fi

    cp "$THEME_DIR/gruvbox/fish/config.fish" "$HOME/.config/fish/"
    cp "$THEME_DIR/gruvbox/picom/picom.conf" "$HOME/.config/picom/"
    cp "$THEME_DIR/gruvbox/polybar/config.ini" "$HOME/.config/polybar/"
    cp "$THEME_DIR/gruvbox/zathura/zathurarc" "$HOME/.config/zathura/"

    # cp -r "$THEME_DIR/gruvbox/rofi" "$HOME/.config/rofi"
    
    sed -i "/colorscheme/c\vim.cmd('colorscheme gruvbox8')" "$HOME/.config/nvim/init.lua"
    sed -i "/airline_theme/c\vim.g.airline_theme = 'base16_gruvbox_dark_hard'" "$HOME/.config/nvim/init.lua"

    if pgrep picom > /dev/null; then
        pkill picom
    fi

    if pgrep polybar > /dev/null; then
        pkill polybar
        while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    fi

    [ "$wm" = "bspwm" ] && bspc wm -r
    [ "$wm" = "i3" ] && i3-msg restart
    [ "$wm" = "bspwm" ] && pkill -USR1 -x sxhkd
    [ "$term" = "kitty" ] && kill -SIGUSR1 $(pgrep kitty)
    [ "$term" = "urxvt" ] && xrdb "HOME/.Xresources"
    clear; exec fish

elif [ "$theme" = "enhanced_productivity" ]; then

    wallpaper="$WALLPAPER_DIR/enhanced_productivity.png"
    nitrogen --set-zoom-fill "$wallpaper" --save > /dev/null 2>&1

    if [ "$term" = "alacritty" ]; then
        check_dir "alacritty"
        cp "$THEME_DIR/enhanced_productivity/alacritty/alacritty.toml" "$HOME/.config/alacritty/"
    elif [ "$term" = "kitty" ]; then
        check_dir "kitty"
        cp "$THEME_DIR/enhanced_productivity/kitty/kitty.conf" "$HOME/.config/kitty/"
    fi

    if [ "$wm" = "i3" ]; then
        check_dir "i3"
        cp "$THEME_DIR/enhanced_productivity/i3/config" "$HOME/.config/i3/"
        if [ "$term" = "kitty" ]; then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/i3/config"
        else
            sed -i 's/kitty/alacritty/g' "$HOME/.config/i3/config"
        fi
    elif [ "$wm" = "bspwm" ]; then
        check_dir "bspwm"
        check_dir "sxhkd"
        cp "$THEME_DIR/enhanced_productivity/bspwm/bspwmrc" "$HOME/.config/bspwm/"
        cp "$THEME_DIR/enhanced_productivity/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/"
        if [ "$term" = "kitty" ];then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/sxhkd/sxhkdrc"
        else 
            sed -i 's/kitty/alacritty/g' "$HOME/.config/sxhkd/sxhkdrc"
        fi
    fi

    cp "$THEME_DIR/enhanced_productivity/fish/config.fish" "$HOME/.config/fish/"
    cp "$THEME_DIR/enhanced_productivity/picom/picom.conf" "$HOME/.config/picom/"
    cp "$THEME_DIR/enhanced_productivity/zathura/zathurarc" "$HOME/.config/zathura/"
    cp "$THEME_DIR/enhanced_productivity/polybar/config.ini" "$HOME/.config/polybar/"

    sed -i "/colorscheme/c\vim.cmd('colorscheme retrobox')" "$HOME/.config/nvim/init.lua"
    sed -i "/airline_theme/c\vim.g.airline_theme = 'base16_gruvbox_dark_hard'" "$HOME/.config/nvim/init.lua"
    if pgrep picom > /dev/null; then
        pkill picom
    fi

    if pgrep polybar > /dev/null; then
        pkill polybar
        while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    fi

    [ "$wm" = "bspwm" ] && bspc wm -r
    [ "$wm" = "i3" ] && i3-msg restart
    [ "$wm" = "bspwm" ] && pkill -USR1 -x sxhkd
    [ "$term" = "kitty" ] && kill -SIGUSR1 $(pgrep kitty)
    clear; exec fish
fi
