#! /bin/bash
ROOT_DIR="$HOME/config-switcher"
SRC_DIR="$HOME/config-switcher/src"
THEME_DIR="$HOME/config-switcher/themes"
WALLPAPER_DIR="$HOME/config-switcher/wallpapers"

> $SRC_DIR/themes.txt

cd $THEME_DIR
for i in *; do
    echo $i >> $SRC_DIR/themes.txt
done

cd "$HOME/config-switcher/src" || exit

./main $SRC_DIR/themes.txt
mapfile -t vars < tmp.txt

theme=${vars[0]}
wm=${vars[1]}
term=${vars[2]}

rm -rf themes.txt
rm -rf tmp.txt

if [ ! -d "$HOME/.config/rofi" ]; then
    cp -r "$ROOT_DIR/globals/rofi" "$HOME/.config/"
fi

if [ ! -d "$HOME/polybar-collection" ]; then
    cp -r "$ROOT_DIR/globals/polybar-collection" "$HOME"
fi

if [ ! -d "$HOME/polybar-scripts" ]; then
    cp -r "$ROOT_DIR/globals/polybar-scripts" "$HOME"
fi

if [ "$theme" = "Catppuccin" ]; then

    wallpaper="$WALLPAPER_DIR/catppuccin.jpg"
    nitrogen --set-zoom-fill "$wallpaper" --save > /dev/null 2>&1
    
    if [ "$term" = "alacritty" ]; then
        cp "$THEME_DIR/Catppuccin/alacritty/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"
    elif [ "$term" = "kitty" ]; then
        cp "$THEME_DIR/Catppuccin/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"
    fi

    # TODO 
    # Change this for the other cases
    if [ "$wm" = "i3" ]; then
        cp "$THEME_DIR/Catppuccin/i3/config" "$HOME/.config/i3/config"
        if [ "$term" = "kitty" ]; then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/i3/config"
        else
            sed -i 's/kitty/alacritty/g' "$HOME/.config/i3/config"
        fi
    elif [ "$wm" = "bspwm" ]; then
        cp "$THEME_DIR/Catppuccin/bspwm/bspwmrc" "$HOME/.config/bspwm/bspwmrc"
        cp "$THEME_DIR/Catppuccin/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/sxhkdrc"
        if [ "$term" = "kitty" ];then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/sxhkd/sxhkdrc"
        else 
            sed -i 's/kitty/alacritty/g' "$HOME/.config/sxhkd/sxhkdrc"
        fi
    fi


    cp "$THEME_DIR/Catppuccin/fish/config.fish" "$HOME/.config/fish/config.fish"
    cp "$THEME_DIR/Catppuccin/picom/picom.conf" "$HOME/.config/picom/picom.conf"
    cp "$THEME_DIR/Catppuccin/zathura/zathurarc" "$HOME/.config/zathura/zathurarc"
    cp "$THEME_DIR/Catppuccin/polybar-collection/launch.sh" "$HOME/polybar-collection/launch.sh"
    cp "$THEME_DIR/Catppuccin/polybar-collection/modules.ini" "$HOME/polybar-collection/modules.ini"
    
    # TODO
    # nvim configuration changes
    # cp "$THEME_DIR/Catppuccin/nvim/init.lua" "$HOME/.config/nvim/init.lua"
    
    if pgrep picom > /dev/null; then
        pkill picom
    fi

    if pgrep polybar > /dev/null; then
        pkill polybar
        while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    fi

    [ "$wm" = "bspwm" ] && bspc wm -r
    [ "$wm" = "i3" ] && i3-msg restart
    [ "$wm" = "bspwm" ] && pkill -USR1 -x sxhkd

    clear; exec fish

elif [ "$theme" = "gruvbox" ]; then

    wallpaper="$WALLPAPER_DIR/gruv.jpg"
    nitrogen --set-zoom-fill "$wallpaper" --save > /dev/null 2>&1

    if [ "$term" = "alacritty" ]; then
        cp "$THEME_DIR/gruvbox/alacritty/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"
    elif [ "$term" = "kitty" ]; then
        cp "$THEME_DIR/gruvbox/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"
    fi

    if [ "$wm" = "i3" ]; then
        cp "$THEME_DIR/gruvbox/i3/config" "$HOME/.config/i3/config"
        if [ "$term" = "kitty" ]; then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/i3/config"
        else
            sed -i 's/kitty/alacritty/g' "$HOME/.config/i3/config"
        fi
    elif [ "$wm" = "bspwm" ]; then
        cp "$THEME_DIR/gruvbox/bspwm/bspwmrc" "$HOME/.config/bspwm/bspwmrc"
        cp "$THEME_DIR/gruvbox/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/sxhkdrc"
        if [ "$term" = "kitty" ];then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/sxhkd/sxhkdrc"
        else 
            sed -i 's/kitty/alacritty/g' "$HOME/.config/sxhkd/sxhkdrc"
        fi
    fi

    cp "$THEME_DIR/gruvbox/fish/config.fish" "$HOME/.config/fish/config.fish"
    cp "$THEME_DIR/gruvbox/picom/picom.conf" "$HOME/.config/picom/picom.conf"
    cp "$THEME_DIR/gruvbox/polybar/config.ini" "$HOME/.config/polybar/config.ini"
    cp "$THEME_DIR/gruvbox/zathura/zathurarc" "$HOME/.config/zathura/zathurarc"

    # cp -r "$THEME_DIR/gruvbox/rofi" "$HOME/.config/rofi"
    
    if pgrep picom > /dev/null; then
        pkill picom
    fi

    if pgrep polybar > /dev/null; then
        pkill polybar
        while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    fi

    [ "$wm" = "bspwm" ] && bspc wm -r
    [ "$wm" = "i3" ] && i3-msg restart
    [ "$wm" = "bspwm" ] && pkill -USR1 -x sxhkd
    clear; exec fish

elif [ "$theme" = "enhanced_productivity" ]; then

    wallpaper="$WALLPAPER_DIR/enhanced_productivity.png"
    nitrogen --set-zoom-fill "$wallpaper" --save > /dev/null 2>&1

    if [ "$term" = "alacritty" ]; then
        cp "$THEME_DIR/enhanced_productivity/alacritty/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"
    elif [ "$term" = "kitty" ]; then
        cp "$THEME_DIR/enhanced_productivity/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"
    fi

    if [ "$wm" = "i3" ]; then
        cp "$THEME_DIR/enhanced_productivity/i3/config" "$HOME/.config/i3/config"
        if [ "$term" = "kitty" ]; then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/i3/config"
        else
            sed -i 's/kitty/alacritty/g' "$HOME/.config/i3/config"
        fi
    elif [ "$wm" = "bspwm" ]; then
        cp "$THEME_DIR/enhanced_productivity/bspwm/bspwmrc" "$HOME/.config/bspwm/bspwmrc"
        cp "$THEME_DIR/enhanced_productivity/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/sxhkdrc"
        if [ "$term" = "kitty" ];then
            sed -i 's/alacritty/kitty/g' "$HOME/.config/sxhkd/sxhkdrc"
        else 
            sed -i 's/kitty/alacritty/g' "$HOME/.config/sxhkd/sxhkdrc"
        fi
    fi

    cp "$THEME_DIR/enhanced_productivity/fish/config.fish" "$HOME/.config/fish/config.fish"
    cp "$THEME_DIR/enhanced_productivity/picom/picom.conf" "$HOME/.config/picom/picom.conf"
    cp "$THEME_DIR/enhanced_productivity/zathura/zathurarc" "$HOME/.config/zathura/zathurarc"
    # cp -r "$THEME_DIR/enhanced_productivity/rofi" "$HOME/.config/rofi"

    if pgrep picom > /dev/null; then
        pkill picom
    fi

    if pgrep polybar > /dev/null; then
        pkill polybar
        while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    fi

    [ "$wm" = "bspwm" ] && bspc wm -r
    [ "$wm" = "i3" ] && i3-msg restart
    [ "$wm" = "bspwm" ] && pkill -USR1 -x sxhkd

    clear; exec fish
fi
