#! /bin/bash
ROOT_DIR="$HOME/config-switcher"
SRC_DIR="$HOME/config-switcher/src"
THEME_DIR="$HOME/config-switcher/themes"
WALLPAPER_DIR="$HOME/config-switcher/wallpapers"

> $SRC_DIR/themes.txt

cd $THEME_DIR
for i in *; do
    echo $i >> $SRC_DIR/themes.txt
done

cd "$HOME/config-switcher/src" || exit

./main
theme=$(cat tmp.txt)

rm -rf themes.txt
rm -rf tmp.txt

if [ "$theme" = "Catppuccin" ]; then

    wallpaper="$WALLPAPER_DIR/catppuccin.jpg"
    nitrogen --set-zoom-fill "$wallpaper" --save
    
    cp "$THEME_DIR/Catppuccin/alacritty/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"

    cp "$THEME_DIR/Catppuccin/bspwm/bspwmrc" "$HOME/.config/bspwm/bspwmrc"
    $HOME/.config/bspwm/bspwmrc

    cp "$THEME_DIR/Catppuccin/fish/config.fish" "$HOME/.config/fish/config.fish"
    cp "$THEME_DIR/Catppuccin/i3/config" "$HOME/.config/i3/config"
    cp "$THEME_DIR/Catppuccin/picom/picom.conf" "$HOME/.config/picom/picom.conf"
    cp "$THEME_DIR/Catppuccin/zathura/zathurarc" "$HOME/.config/zathura/zathurarc"
    cp "$THEME_DIR/Catppuccin/polybar-collection/launch.sh" "$HOME/polybar-collection/launch.sh"
    cp "$THEME_DIR/Catppuccin/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/sxhkdrc"
    cp "$THEME_DIR/Catppuccin/polybar-collection/launch.sh" "$HOME/polybar-collection/launch.sh"
    cp "$THEME_DIR/Catppuccin/polybar-collection/modules.ini" "$HOME/polybar-collection/modules.ini"
    
    # TODO
    # nvim configuration changes
    # cp "$THEME_DIR/Catppuccin/nvim/init.lua" "$HOME/.config/nvim/init.lua"
    
    if ! pgrep picom > /dev/null; then
        picom --experimental-backends -b
    else 
        pkill picom; picom --experimental-backends -b

    fi
    if ! pgrep polybar > /dev/null; then
        $HOME/polybar-collection/launch.sh > /dev/null 2>&1
    else
        pkill polybar
        $HOME/polybar-collection/launch.sh > /dev/null 2>&1
    fi

    pkill -USR1 -x sxhkd

elif [ "$theme" = "gruvbox" ]; then
    wallpaper="$WALLPAPER_DIR/gruv.jpg"
    nitrogen --set-zoom-fill "$wallpaper" --save

    cp "$THEME_DIR/gruvbox/alacritty/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"

    cp "$THEME_DIR/gruvbox/bspwm/bspwmrc" "$HOME/.config/bspwm/bspwmrc"
    $HOME/.config/bspwm/bspwmrc

    cp "$THEME_DIR/gruvbox/fish/config.fish" "$HOME/.config/fish/config.fish"
    cp "$THEME_DIR/gruvbox/i3/config" "$HOME/.config/i3/config"
    cp "$THEME_DIR/gruvbox/picom/picom.conf" "$HOME/.config/picom/picom.conf"
    cp "$THEME_DIR/gruvbox/zathura/zathurarc" "$HOME/.config/zathura/zathurarc"
    cp "$THEME_DIR/gruvbox/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/sxhkdrc"
    cp "$THEME_DIR/gruvbox/polybar-collection/launch.sh" "$HOME/polybar-collection/launch.sh"
    cp "$THEME_DIR/gruvbox/polybar-collection/modules.ini" "$HOME/polybar-collection/modules.ini"
    
    if ! pgrep picom > /dev/null; then
        picom --experimental-backends -b
    else 
        pkill picom; picom --experimental-backends -b
    fi
    if ! pgrep polybar > /dev/null; then
        $HOME/polybar-collection/launch.sh > /dev/null 2>&1
    else
        pkill polybar
        $HOME/polybar-collection/launch.sh > /dev/null 2>&1
    fi

    pkill -USR1 -x sxhkd
fi
